name: Check CODEOWNERS for Committer

on:
  push:
    branches:
      - main

jobs:
  check-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Committer Username
        id: committer_username
        run: |
          git log -1 --pretty=format:'%ae' | awk -F "+" '{print $2}' | awk -F "@" '{print $1}' | tr '[:upper:]' '[:lower:]'
          # Extracts the GitHub username associated with the latest commit

      - name: Check if Committer is in CODEOWNERS
        id: check_codeowners
        run: |
          committer_username="${{ steps.committer_username.outputs.stdout }}"
          echo $committer_username
          owners=$(awk '/^\*.*@/ {print $2}' CODEOWNERS)
          if echo "$owners" | grep -qw "$committer_username"; then
            echo "Committer is in CODEOWNERS"
          else
            echo "Committer is not in CODEOWNERS"
          fi

