name: Sync Templates to S3 - dev

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  sync_to_s3_for_exist_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Check CODEOWNERS
        id: check_codeowners
        run: |
          USERNAME=$(echo "${{ github.actor }}" | sed 's/[^a-zA-Z0-9]//g') # Sanitize username for API call
          CODEOWNERS_CONTENT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/contents/CODEOWNERS")
          if echo "${CODEOWNERS_CONTENT}" | grep -q "\\b${USERNAME}\\b"; then
            echo "User '${USERNAME}' is in CODEOWNERS"
            echo "::set-output name=codeowner::true"
          else
            echo "User '${USERNAME}' is not in CODEOWNERS"
            echo "::set-output name=codeowner::false"
          fi

