name: Sync Templates to S3 - dev

on:
  pull_request:
    types: [opened]
    paths:
      - 'templates/ADO/**'
      - 'templates/ServiceNow/**'
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  file_changes:
    name: File changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Changed Files
        id: changed_files
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}:${{ github.event.pull_request.head.ref }}
          git checkout ${{ github.event.pull_request.head.ref }}
          changed_files=$(git log --oneline --name-status -m -- templates/)
          username=${{ github.event.pull_request.user.login }}
          latest_file=$(echo "$changed_files" | grep -E "^[AMD]\s" | head -n 1 | awk '{$1=""; print $0}' | sed 's/^[ \t]*//')
          echo "::set-output name=file::$latest_file"
          echo "::set-output name=committer::$username"
 
      - name: Check CODEOWNERS file
        id: codeowners_file
        run: |
          echo ${{ steps.changed_files.outputs.file }}
          echo ${{ steps.changed_files.outputs.committer }}
          while IFS= read -r line; do
            if echo "$line" | grep -q "${{ steps.changed_files.outputs.file }}.*@${{ steps.changed_files.outputs.committer }}"; then
              echo "Record is exists"
              echo "::set-output name=mode::no"
              exit 0
            fi
          done < CODEOWNERS
          echo "Record doesn't exist"
          echo "::set-output name=mode::add"
  
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     role-to-assume: arn:aws:iam::721101776339:role/DevOps_Platforms_GitHub_Actions_Assume_Role
      #     aws-region: eu-central-1
      #     role-skip-session-tagging: false

      # - name: Sync ADO templates to S3
      #   run: |
      #     aws s3 sync templates/ADO/ s3://tf-s3-ado-snow-sync-staging/ADO/
  
      # - name: Sync ServiceNow templates to S3
      #   run: |
      #     aws s3 sync templates/ServiceNow/ s3://tf-s3-ado-snow-sync-staging/ServiceNow/
        
    outputs:
      mode: ${{ steps.codeowners_file.outputs.mode }}
      file: ${{ steps.changed_files.outputs.file }}
      username: ${{ steps.changed_files.outputs.committer }}

  add_to_codeowners:
    if: ${{ needs.file_changes.outputs.mode == 'add' }}
    runs-on: ubuntu-latest
    needs: file_changes
    steps:        
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Add record to the CODEOWNERS
        run: |
          echo ${{ needs.file_changes.outputs.file }}
          echo ${{ needs.file_changes.outputs.username }}
          printf "/%s\t@%s\n" "${{ needs.file_changes.outputs.file }}"	"${{ needs.file_changes.outputs.username }}" >> CODEOWNERS

      - name: Commit changes
        run: |
          git config --local user.email "syakovenko81@github.com"
          git config --local user.name "syakovenko81"
          git add CODEOWNERS
          git commit -m "Update CODEOWNERS file"
          git push

