name: Sync Templates to S3 - dev

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  code-review:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get CODEOWNERS
        run: |
          git fetch origin main
          git checkout origin/main -- CODEOWNERS
          # Adjust the path if your CODEOWNERS file is located in a different directory

      - name: Check code ownership
        id: codeowners
        run: |
          changed_files=$(git diff --name-only origin/main...HEAD)
          echo $changed_files
          # while IFS= read -r file; do
          #     if grep -q "^$file\s.*" CODEOWNERS; then
          #         echo "false"
          #         exit 0
          #     fi
          # done <<< "$changed_files"
          # echo "true"


      - name: Request review if necessary
        if: steps.codeowners.outputs.needs_review == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.pulls.createReviewRequest({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: ['reviewer1', 'reviewer2'] // Add your reviewers here
            });
            console.log(response);
