name: Check CODEOWNERS for Committer

on:
  push:
    branches:
      - main

jobs:
  check-codeowners:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get CODEOWNERS
        run: |
          git fetch origin main
          git checkout origin/main -- CODEOWNERS
          # Adjust the path if your CODEOWNERS file is located in a different directory

      - name: Get Committer Username
        id: committer_username
        run: |
          echo "::set-output name=username::$(git log -1 --pretty=format:'%an')"
          # This command retrieves the committer's username of the latest commit

      - name: Check if Committer is in CODEOWNERS
        id: check_codeowners
        run: |
          committer=$(cat $GITHUB_WORKSPACE/CODEOWNERS | grep -Eo '@\S+' | sed 's/@//')
          committer_username="${{ steps.committer_username.outputs.username }}"
          if [[ "$committer" == *"$committer_username"* ]]; then
            echo "Committer is in CODEOWNERS"
          else
            echo "Committer is not in CODEOWNERS"
          fi
